version: "3"
services:
  db:
    container_name: sql_server_db
    image: mcr.microsoft.com/mssql/server
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Password12"
      ACCEPT_EULA: "Y"
  